# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Coco-pomelo
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl:  # the subpath of the site
url: "https://cjs0721.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: 792333803@qq.com
      link: "#"
    - name: WeChat
      value: wmsgj_07211212
      link: "#"
  follow:
    - name: Twitter
      link: "#"
      username: "@YourTwitterUsername"
    - name: Facebook
      link: "#"
    - name: LinkedIn
      link: "#"
    - name: GitHub
      link: https://github.com/CJS0721
    - name: Dribbble
      link: "#"
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
